{{- if .Values.cluster.enabled }}
{{- $ns := default .Values.cluster.namespace .Values.namespace.name -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ $ns }}
spec:
  instances: {{ .Values.cluster.instances }}
  primaryUpdateStrategy: {{ .Values.cluster.primaryUpdateStrategy }}
  resources:
{{- toYaml .Values.cluster.resources | nindent 4 }}
  storage:
    size: {{ .Values.cluster.storage.size }}
  bootstrap:
    initdb:
      database: {{ .Values.cluster.bootstrap.initdb.database }}
      owner: {{ .Values.cluster.bootstrap.initdb.owner }}
{{- end }}
