{{- if .Values.observability.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg-operator
  namespace: {{ .Values.observability.namespace }}
  labels:
    release: {{ .Values.observability.releaseLabel }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.observability.operatorNamespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  podMetricsEndpoints:
    - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg-clusters
  namespace: {{ .Values.observability.namespace }}
  labels:
    release: {{ .Values.observability.releaseLabel }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.cluster.namespace }}
  selector:
    matchLabels:
      {{ .Values.observability.clusterSelector.labelKey }}: {{ .Values.observability.clusterSelector.labelValue }}
  podMetricsEndpoints:
    - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cnpg-basic-alerts
  namespace: {{ .Values.observability.namespace }}
  labels:
    release: {{ .Values.observability.releaseLabel }}
spec:
  groups:
    - name: cnpg.basic
      rules:
        - alert: CnpgOperatorDown
          expr: up{job=~"cnpg-operator.*"} == 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: CNPG operator is not scraping
            description: Prometheus has not scraped the CNPG operator for 5 minutes.
        - alert: CnpgInstanceDown
          expr: up{job=~"cnpg-clusters.*"} == 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: CNPG instance is not scraping
            description: Prometheus has not scraped a CNPG instance for 5 minutes.
{{- end }}
